
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qwakkghefgahtycxzsfe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF3YWtrZ2hlZmdhaHR5Y3h6c2ZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4ODk4ODYsImV4cCI6MjA2NTQ2NTg4Nn0.1MNyB77zBMIDcXZCSGmrnm9mfRNcqTi0iZcN7MFj4RQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce'
  }
});
